### ISSUE TITLE
Doc issue regarding DNF module requirements

### ISSUE THREAD

**Issue by jcberthon** [ansible/ansible-modules-extras#1032]
The current documentation (and comments in the source code of the module) regarding DNF states that the only dependencies are: python, dnf and optionally yum-utils.

Actually there is another important dependency: python-dnf.

I have a Fedora 22 server and I'm testing the Fedora 23 beta server as well, both do not ship by default with python-dnf (I'm installing the minimum server configuration). And my ansible playbook fails miserably:

```
Traceback (most recent call last):
  File "/home/deploy/.ansible/tmp/ansible-tmp-1443355880.90-234567412888527/dnf", line 25, in <module>
    import dnf
ImportError: No module named dnf
```

The **documentation** (and **source code comments**) should be updated to mentioned that **python-dnf** is a **requirement**.

**Comment by bcoca** [comment]
i believe that is exactly what the requirements are referring to, the 'dnf' python library

**Comment by jcberthon** [comment]
That is not clear at all because of the following:
- there exists a dnf package
- it is not mentioned that requirements are Python modules 
- apt module is referring to python-apt and not apt
- apt module is referring to aptitude which is not a python module but the aptitude package, as far as I can tell 

So either the doc should state python-dnf or a sentence should state "the followings are required Python modules to be installed on the remote node". 

And of course modules docs should be consistent in this respect.

**Comment by abadger** [comment]
Thanks for pointing that out.  I've updated the documentation in the repository.  It will refresh on the website the next time we do a docs rebuild.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
