### ISSUE TITLE
New Module - AWS Cloudfront

### ISSUE THREAD

**Issue by Etherdaemon** [ansible/ansible-modules-extras#1221]
I am planning on implementing a module to implement the main AWS Cloudfront features.

These include actions for distributions, streaming distributions, origin_access_ids:
- creating
- updating 
- deleting .

Also the inclusion of creation of invalidations against distributions.

**Comment by robynbergeron** [comment]
@Etherdaemon -- Thanks for submitting this feature idea.

We encourage all Ansible community members to submit pull requests to satisfy feature requests. If anyone is interested in contributing this as a new module, you can consult the module guidelines (http://docs.ansible.com/ansible/developing_modules.html) for more information.

And it looks like you have already done just that :) -- looks like #1223 is your new module submission for this feature idea! I'm going to go ahead and close this issue since you've created a PR. LMK if you feel otherwise :)

Cheers, and thanks!
