### ISSUE TITLE
'expect' module does not detect pexect python module when in a virtualenv

### ISSUE THREAD

**Issue by crainiarc** [ansible/ansible-modules-extras#1300]
In order to keep my python modules organized, I usually set up a virtualenv before installing my python modules. For my ansible script, I have a virtualenv with the following python modules:
- paramiko
- PyYAML
- Jinja2
- httplib2
- pexpect

When I run my ansible script (which uses the expect module), I get the following error:
`The pexpect python module is required`
Thus suggesting that the pexpect module was not installed. However, when I try to import pexpect in a separate python script within the virtualenv, I was able to do so.

I was only able to run my ansible script after I have installed pexpect in my global environment. Is there a way to use the expect module without install pexpect in the global environment?

**Comment by mscherer** [comment]
Hi, 

I think this question should rather go the ansible user mailling list ( https://groups.google.com/forum/#!forum/ansible-project ), since that's not a bug report or a issue. 

I suspect there is a way by using a different ansible_python ( as explained on https://stackoverflow.com/questions/20575084/best-way-to-always-run-ansible-inside-a-virtualenv-on-remote-machines ), but people on the list might be better at explaining.

Can you close that issue once you post there ?

**Comment by bcoca** [comment]
# List Information

Hi!

Thanks very much for your interest in Ansible.  It sincerely means a lot to us. 

This appears to be a user question, and we'd like to direct these kinds of things to either the mailing list or the IRC channel.
- IRC: #ansible on irc.freenode.net  
- mailing list: https://groups.google.com/forum/#!forum/ansible-project

If you can stop by there, we'd appreciate it.  This allows us to keep the issue tracker for bugs, pull requests, RFEs and the like.

In any case, you don't need the library in the virtualenv that executes ansible, but in the python that executes the module on the 'target' machine.

Thank you once again and we look forward to seeing you on the list or IRC.  Thanks!

**Comment by JLofgren** [comment]
@crainiarc, did you get an answer to your question from the mail list? Can you provide a permalink?
