### ISSUE TITLE
DepsolveError on dnf absent

### ISSUE THREAD

**Issue by leocrawford** [ansible/ansible-modules-extras#1517]
I've just upgraded to ansible 2.0.0.1, from the latest version (1.9.?) and

```
- name: remove packages 
  package: name={{item}} state=absent
  with_items:
   - libreoffice-core
```

now produces:

> failed: [default] => (item=[u'libreoffice-core']) => {"failed": true, "item": ["libreoffice-core"], "module_stderr": "", "module_stdout": "\r\nTraceback (most recent call last):\r\n File \"/home/vagrant/.ansible/tmp/ansible-tmp-1452957073.18-202826278311962/dnf\", line 2284, in \r\n main()\r\n File \"/home/vagrant/.ansible/tmp/ansible-tmp-1452957073.18-202826278311962/dnf\", line 345, in main\r\n ensure(module, base, params['state'], params['name'])\r\n File \"/home/vagrant/.ansible/tmp/ansible-tmp-1452957073.18-202826278311962/dnf\", line 296, in ensure\r\n if not base.resolve():\r\n File \"/usr/lib/python2.7/site-packages/dnf/base.py\", line 547, in resolve\r\n raise exc\r\ndnf.exceptions.DepsolveError: package libreoffice-xsltfilter-1:5.0.0.5-2.fc23.x86_64 requires libreoffice-core = 1:5.0.0.5-2.fc23, but none of the providers can be installed\r\n", "msg": "MODULE FAILURE", "parsed": false}

If I do

```
sudo dnf remove libreoffice-core
```

from the command line then it works fine.

**Comment by abadger** [comment]
\cc @ignatenkobrain @DJMuggs I just fixed this with: b1e9dc0b52b3bb0d44bf78b6e3797dfc82e21fda

Could you guys take a look at it?  I'm not sure if allow_erasing needs to be set only for removals or if it should always be set.  Doing it only for removals seemed the safest route to get this fixed in 2.0.1 but if you think it should be set in other cases/always we can definitely update the code for those circumstances.
