### ISSUE TITLE
vca_vapp missing documentation

### ISSUE THREAD

**Issue by dan-petty** [ansible/ansible-modules-extras#1600]
Documentation for the vca_vapp module ( http://docs.ansible.com/ansible/vca_vapp_module.html ) is missing several options:
api_version
catalog_name
host
instance_id
org
password
service_type
username

[module: cloud/vmware/vca_vapp.py]

**Comment by dan-petty** [comment]
https://github.com/ansible/ansible-modules-extras/pull/1601

**Comment by nitzmahone** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
