### ISSUE TITLE
Bower and DNF modules not in PPA package

### ISSUE THREAD

**Issue by tborealis** [ansible/ansible-modules-extras#163]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8.2
##### Environment:

Ubuntu 14.10 (package installed using official PPA)
##### Summary:

The Bower and DNF modules are not included in the official PPA package.
##### Steps To Reproduce:
1. Install Ansible from PPA
2. `dpkg -L ansible | grep 'bower\|dnf'`
##### Expected Results:

```
/usr/share/pyshared/ansible/modules/extras/packaging/bower.py
/usr/share/pyshared/ansible/modules/extras/packaging/dnf.py
```
##### Actual Results:

Nothing - modules are not included in the distribution.

**Comment by tborealis** [comment]
Further to this I notice neither module are in the `release1.8.0`, `release1.8.1` or `release1.8.2`  branches. They are however documented [here](http://docs.ansible.com/bower_module.html) and [here](http://docs.ansible.com/dnf_module.html) as being available in 1.7 and 1.8 respectively.

**Comment by bcoca** [comment]
they were added in 1.9, but the docs were set to older versions

**Comment by tborealis** [comment]
Given that 1.9 is not yet released, should these be in the docs at all at this point?

**Comment by bcoca** [comment]
The above PR should fix the docs issue, once we push them again to the site

**Comment by jkbrzt** [comment]
The same is true for Homebrew-installed Ansible.

The actual error message to make it easier to Google:

> ERROR: bower is not a legal parameter in an Ansible task or handler
> Ansible failed to complete successfully. Any error output should be
> visible above. Please fix these errors and try again.

**Comment by abadger** [comment]
1.9 has been released with bower and dnf modules.  So this should now be fixed.

# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!
