### ISSUE TITLE
maven_artifact - No module named lxml

### ISSUE THREAD

**Issue by emeraldjava** [ansible/ansible-modules-extras#1639]
Hi,

I've running a simple maven_artifact with ansible versnio 2.0.0.2

```
ansible all --inventory-file=inventory/eirtest01.yml -m maven_artifact -a "group_id=junit artifact_id=junit dest=/tmp/junit-latest.jar" -vv
```

The command fails with an error which i believe is related to the python script, which cannot access the 'lxml' python library.

```
test01vm1 | FAILED! => {
    "changed": false, 
    "failed": true, 
    "module_stderr": "", 
    "module_stdout": "\r\nTraceback (most recent call last):\r\n  File \"/home/admin123/.ansible/tmp/ansible-tmp-1455018862.7-24328596963413/maven_artifact\", line 25, in <module>\r\n    from lxml import etree\r\nImportError: No module named lxml\r\n", 
    "msg": "MODULE FAILURE", 
    "parsed": false
}
```

I've attempted to check the python path using this command

```
- name: "Getting PYTHONPATH"
  local_action: shell python -c 'import sys; print(":".join(sys.path))'
  register: pythonpath

- name: print pythonpath
  debug: var=pythonpath
```

but i cannot see anything out of the ordinary here. 

```
TASK [print pythonpath] ********************************************************
ok: [test01vm1] => {
    "pythonpath": {
    "changed": true, 
    "cmd": "python -c 'import sys; print(\":\".join(sys.path))'", 
    "delta": "0:00:00.024019", 
    "end": "2016-02-09 12:00:48.023837", 
    "rc": 0, 
    "start": "2016-02-09 12:00:47.999818", 
    "stderr": "", 
    "stdout": ":/usr/lib/python2.7:/usr/lib/python2.7/plat-x86_64-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PILcompat:/usr/lib/python2.7/dist-packages/gtk-2.0:/usr/lib/pymodules/python2.7:/usr/lib/python2.7/dist-packages/ubuntu-sso-client:/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode", 
    "stdout_lines": [
        ":/usr/lib/python2.7:/usr/lib/python2.7/plat-x86_64-linux-gnu:/usr/lib/python2.7/lib-tk:/usr/lib/python2.7/lib-old:/usr/lib/python2.7/lib-dynload:/usr/local/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages:/usr/lib/python2.7/dist-packages/PILcompat:/usr/lib/python2.7/dist-packages/gtk-2.0:/usr/lib/pymodules/python2.7:/usr/lib/python2.7/dist-packages/ubuntu-sso-client:/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode"
    ], 
    "warnings": []
    }
}
```

Do i need to do some extra configuration to ensure the lxml library is on the 'configured module search path' for my ansible process?

**Comment by nagromydna** [comment]
I ran into the same issue.  Turns out I didn't have lxml installed.  Fixed it by running ansible -i [your_inventory_file] [the_server_you_are_copying_to] -m yum -a "name=python-lxml state=installed".  I realize this won't work for you if you are using yum, but hopefully you have a method to see if python-lxml is installed.

**Comment by nagromydna** [comment]
*aren't using yum

**Comment by nitzmahone** [comment]
# Is This A Bug?

Hi!

Thanks very much for your submission to Ansible.  It sincerely means a lot to us.

We're not sure this is a bug, and we don't mean for this to be confrontational.  Let's explain what we're thinking: You'll need lxml installed somehow on the target machine, whether via (your OS package manager of choice), pip, easy_install, or manual installation to a location on the Python path. 

As such, we're going to close this ticket.  However, we're open to being corrected, should you wish to discuss.  You can stop by one of our two mailing lists 
to talk about this and we might be persuaded otherwise.
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Comments on closed tickets aren't something we monitor, so if you do disagree with this, a mailing list thread is probably appropriate.

Thank you once again for this and your interest in Ansible!

**Comment by emeraldjava** [comment]
Thanks for the support. I realise now that the ansible 'maven-artifact' command was being executed on the remote target machine rather than the ansible host, which i had expected. As mentioned above the remote machine did not have the required lxml library installed. For reference I added 'local_action:' to ensure that the 'maven-artifact' ran on the local machine.
