### ISSUE TITLE
win_chocolatey doc vs module

### ISSUE THREAD

**Issue by abdulg** [ansible/ansible-modules-extras#254]
The documentation says the package name is passed in a parameter called 'package', but when running the devel version, it complains that the parameter 'name' is expected

**Comment by robynbergeron** [comment]
Hi @abdulg -- 

The documentation now appears to be correctly synchronized, with both the docs and the module citing the parameter 'name'. I think the issue here was that the documentation was for the (at that point) released version, and the devel version at that time had differences (changed in #134).

Copying the win_chocolately maintainers for good measure - @trondhindenes @petemounce @elventear @smadam813 - but I am going to go ahead and close this out as it should now be resolved. @abdulg -- if you still have this problem for some reason, let us know!

(And sorry it took so long to respond.)
