### ISSUE TITLE
Suggestion: allow #channel override for @user

### ISSUE THREAD

**Issue by jmccown** [ansible/ansible-modules-extras#322]
##### ISSUE TYPE

Bug Report
##### COMPONENT NAME

slack
##### ANSIBLE VERSION

1.8.4
##### SUMMARY

The slack webhooks page notes that overriding the channel #channel with @username allows direct messages, but the current slack.py prepends # if channel[0] isn't #  --Tested with (1.8.4)

payload['channel'] = channel if (channel[0] in '#@') else '#'+channel
- J

**Comment by ramondelafuente** [comment]
This seems to be fixed in https://github.com/ansible/ansible-modules-extras/pull/218

**Comment by robynbergeron** [comment]
Hi @jmccown -- Thanks for submitting this bug report. Apologies for taking so long to triage it. Since this bug has been open for a while, we would appreciate if you can verify if you are still seeing the reported behavior in the latest version.

If you are seeing the reported behavior, just let us know and we will leave the bug open and notify the module maintainer.

If you are no longer seeing the reported behavior, please let us know and we will close the bug report. @ramondelafuente commented that it seems to be fixed, just want to verify / make sure you know.

Thanks! :)

**Comment by jctanner** [comment]
Closing due to submitter timeout.
