### ISSUE TITLE
add feature to only update mongodb password on create

### ISSUE THREAD

**Issue by solomongifford** [ansible/ansible-modules-extras#364]
I have a scenario where I want a playbook to only set the a mongodb user's password on creation. The user module supports the update_password which can be set to on_create which "will only set the password for newly created users. (added in Ansible 1.3)"  The mysql_user module now supports that as well.  

I will be submitting a merge request for this.

**Comment by robynbergeron** [comment]
Hi @solomongifford: thanks for submitting this feature idea, and the subsequent merge request for your feature idea. Much appreciated!

Sorry it took us a while to triage this issue -- but it looks like the story had a happy ending since @gregdek merged your code back in June. (Thanks, @gregdek :D) 

Closing this out since it looks like all is resolved here.

**Comment by robynbergeron** [comment]
.....and now I'm actually going to hit the close button rather than just the comment button. :)
