### ISSUE TITLE
firewalld module traces when port does not include protocol

### ISSUE THREAD

**Issue by sivel** [ansible/ansible-modules-extras#404]
When using the firewalld module, if you omit the protocol in the `port` argument, you will get a traceback from the following line:

https://github.com/ansible/ansible-modules-extras/blob/09fc1eefe5861a8191c8b89d1c48f09a7fb29558/system/firewalld.py#L237

Since all tracebacks are "bugs" we should probably catch this and say something more helpful.

**Comment by gregdek** [comment]
[module: system/firewalld.py]

**Comment by gregdek** [comment]
Thanks for submitting this bug report. Apologies for taking so long to triage it. Since this bug has been open for a while, we would appreciate if you can verify if you are still seeing the reported behavior in the latest version.

If you are seeing the reported behavior, just let us know and we will leave the bug open and notify the module maintainer.

If you are no longer seeing the reported behavior, please let us know and we will close the bug report.

**Comment by robynbergeron** [comment]
Hi @sivel -- I think this should now be fixed, courtesy of @ag-wood and #1031, which has been merged.

If not, let us know. :)

cc: @maxamillion for your FYI :)
