### ISSUE TITLE
pkgin failes to ensure packages are present

### ISSUE THREAD

**Issue by cmacrae** [ansible/ansible-modules-extras#475]
### Basic Info

Ansible version: 1.9.1
OS: SmartOS 15.1.0
pkgin version: `pkgin 0.8.0 for SunOS-5.11 x86_64 (using SQLite 3.8.8.3)`
### Applied Ansible code

``` yaml
  - name: Ensure dependencies are installed
    pkgin: name={{ item }} state=present
    with_items:
      - build-essential
      - ruby22-base
```
### Results

```
TASK: [rolename | Ensure dependencies are installed] *********************** 
failed: [host.my.domain] => (item=build-essential) => {"failed": true, "item": "build-essential"}
msg: failed to install build-essential:
.......................................................
<_snip_> __(pkgin output of install process)__ < /snip >
.......................................................
installing automake-1.15...
installing autoconf-2.69nb5...
installing build-essential-1.1...
pkg_install warnings: 0, errors: 0
reading local summary...
processing local summary...

marking build-essential-1.1 as non auto-removable

failed: [host.my.domain] => (item=ruby22-base) => {"failed": true, "item": "ruby22-base"}
msg: failed to install ruby22-base: ===========================================================================
$NetBSD: MESSAGE,v 1.1 2015/03/08 16:24:55 taca Exp $

Note that this is a minimal package.

The original ruby-2.2.2 distribution includes more extension
libraries, some of which are provided as separate packages:

        databases/ruby-gdbm:            GDBM module
        devel/ruby-fiddle:              Fiddle module
        devel/ruby-readline:            readline module
        x11/ruby-tk:                    Tk modules

===========================================================================
calculating dependencies... done.

nothing to upgrade.
2 packages to be installed (9112K to download, 26M to install):

libyaml-0.1.6nb1 ruby22-base-2.2.2

downloading packages...
download started.
download ended.
download started.
download ended.
installing packages...
installing libyaml-0.1.6nb1...
installing ruby22-base-2.2.2...
pkg_install warnings: 0, errors: 0
reading local summary...
processing local summary...

marking ruby22-base-2.2.2 as non auto-removable


FATAL: all hosts have already failed -- aborting
```
### Results of subsequent runs

```
TASK: [rolename | Ensure dependencies are installed] *********************** 
failed: [host.my.domain] => (item=build-essential) => {"failed": true, "item": "build-essential"}
calculating dependencies... done.ntial: 
nothing to do.

failed: [host.my.domain] => (item=ruby22-base) => {"failed": true, "item": "ruby22-base"}
calculating dependencies... done.e: 
nothing to do.


FATAL: all hosts have already failed -- aborting
```
### Investigation

The packages are in fact installed.
Manual installation of the packages prior to applying this play to the server, then running the play still result in the above failure.

**Comment by cmacrae** [comment]
After switching to the comma separated syntax, as documented in the source:  

> name:
>        description:
>            - Name of package to install/remove;
>            - multiple names may be given, separated by commas
>        required: true

This still fails, now with the following output:

```
TASK: [rolename | Ensure dependencies are installed] *********************** 
failed: [host.my.domain] => {"failed": true}
calculating dependencies... done.ntial: 
nothing to do.


FATAL: all hosts have already failed -- aborting
```

Running my playbook with `-vvvvv` yields no further detail for the `pkgin` play, I'm afraid.

**Comment by cmacrae** [comment]
Please ignore this issue report.  
Although this behavior seems to be exhibited with Ansible version 1.9.1, replacing the `pkgin.py` module with that from development works fine.

**Comment by athak** [comment]
This issue is still present in Ansible 1.9.2. Had to revert to Ansible 1.6 (from package) to be able to use the pkgin module.

**Comment by cehoffman** [comment]
For those that come after me. The secret appears to be that the pkgin module expects to take a name that doesn't have a version number after it.

For illustration I was trying to install the package `transmission-2.84` using `pkgin: name=transmission-2.84`. This failed after the first install with the above "nothing to do" problem because the module was failing to detect the package was already installed.

If you look at the source [here](https://github.com/ansible/ansible-modules-extras/blob/fa11718c0f6632dc9b1117c6887f43df6dd60186/packaging/os/pkgin.py#L116) you can see that the regular expression removes suffixes that are numbers only. Changing the action to `pkgin: name=transmission` solved the problem.

**Comment by cehoffman** [comment]
For those that come after me. The secret appears to be that the pkgin module expects to take a name that doesn't have a version number after it.

For illustration I was trying to install the package `transmission-2.84` using `pkgin: name=transmission-2.84`. This failed after the first install with the above "nothing to do" problem because the module was failing to detect the package was already installed.

If you look at the source [here](https://github.com/ansible/ansible-modules-extras/blob/fa11718c0f6632dc9b1117c6887f43df6dd60186/packaging/os/pkgin.py#L116) you can see that the regular expression removes suffixes that are numbers only. Changing the action to `pkgin: name=transmission` solved the problem.

I don't have enough experience with pkgin to know if this is good, but my instinct right now is in favor. I was initially disappointed thinking I would have to update the task for a bump in the package which this solves.
