### ISSUE TITLE
[lvol module] shrinking lv : regression

### ISSUE THREAD

**Issue by tgermain** [ansible/ansible-modules-extras#513]
#### Ansible Version:

ansible 1.9.1 <- not working 
ansible 1.7.x <- working 
#### Ansible Configuration:

No custom configuration
#### Environment:

CentOs 6,7
#### Summary:

Using the _lvol_ module to shrink a logical volume result in an error.

 It's seems that the cause of the problem is d11e36589aec62ea27cd5ab4f84e7e9df46d8e2b.

in system/lvol.py:216 :

``` python
tool = 'lvreduce --force'
```

is replaced by 

``` python
tool = module.get_bin_path("lvextend", required=True)
tool.append("--force")
```
##### **First problem** :

How `lvextend` is supposed to reduce a logical volume ? 

I try to use lvextend by feeding its with parameters to reduce a volume ( example : `sudo lvextend -L 1G --force /dev/mvg/test`). 

It return `New size given (256 extents) not larger than existing size (512 extents)`.
The behaviour of `lvextend` is perfectly fine.
##### **Second problem** :

`module.get_bin_path("lvextend", required=True)` return a string.

There's no method `append()` for strings which cause the failure.
#### Steps To Reproduce:

Assuming `mvg` is an existing volume group with enough free space

Create a test logical volume with

``` bash
sudo lvcreate -n test -L 2G mvg
```

then execute 

``` yaml
- hosts: localhost
  tasks: 
    - name: reducing size of an lv volume
      lvol: vg=mvg lv=test size=1G force=yes
```

to reduce the size of the test volume to 1G
#### Expected Results:

The test volume is shrinked, at least an error if the force parameter is not set to true.
#### Actual Results:

```
failed: [localhost] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1432040030.03-150118546708805/lvol", line 1838, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1432040030.03-150118546708805/lvol", line 220, in main
    tool.append("--force")
AttributeError: 'str' object has no attribute 'append'

```

**Comment by abadger** [comment]
Thanks!  From the commit you link to it looks like a typo in that set of changes.  Working up a fix.

**Comment by abadger** [comment]
# Closing This Ticket

Hi!

We believe recent commits (likely detailed above) should resolve this question or problem for you.

This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular
issue is resolved.

Thank you!

**Comment by ggrossetie** [comment]
Hello @tgermain, I'm stuck with the same issue, did you find a workaround ?
@abadger Do you know if this fix will be available in Ansible 1.9.2 or in Ansible 2.0 ? 

Thanks

**Comment by bcoca** [comment]
it will be in 2.0 and possibly in a 1.9.3 if we end up releasing one.

**Comment by tgermain** [comment]
@Mogztter I'm using a `command` module and rely on lvol CLI instead.

**Comment by ggrossetie** [comment]
Thanks your replies.
@tgermain Ok I think I will do the same :smile:
