### ISSUE TITLE
homebrew_cask fails on hidden directories

### ISSUE THREAD

**Issue by jburwell** [ansible/ansible-modules-extras#699]
The `validate_path` function in the `homebrew_cask.py` does not allow directories starting with a ".".  For example, the module will with an invalid homebrew path error when Homebrew is installed in ``~./homebrew".

**Comment by robynbergeron** [comment]
Hey there, Mr. Burwell! :)

Just doing a bit of housecleaning. Looks like #701 got merged a while ago... and since it was your bug report and PR, I'm going to assume that this fixed your issue and close this out.  If for some reason you don't think it's ready to be closed out, just let us know!

Thanks for your contribution -- hope all is well with you :)
