### ISSUE TITLE
Failed to validate the SSL certificate for Slack

### ISSUE THREAD

**Issue by jure** [ansible/ansible-modules-extras#82]
##### Issue Type:

Bug Report
##### Ansible Version:

ansible 1.8
##### Environment:

OS X 10.10, Python 2.7.8 installed with homebrew.
##### Summary:

Certificate validation for Slack fails for some reason. It shouldn't, as the certificates are valid.
##### Steps To Reproduce:

Add a Slack notification to your playbook and play it:

```
    - name: Send notification to Slack
      local_action:
        module: slack
        domain: mediately.slack.com
        token: placeholder
        msg: "EC2 instance killed."
```
##### Expected Results:

A Slack notification.
##### Actual Results:

I get a certificate validation failure:

```
TASK: [Send notification to Slack] ******************************************** 
failed: [127.0.0.1 -> 127.0.0.1] => {"failed": true}
msg: Failed to validate the SSL certificate for mediately.slack.com:443. Use validate_certs=no or make sure your managed systems have a valid CA certificate installed. Paths checked for this platform: /etc/ssl/certs, /etc/ansible

FATAL: all hosts have already failed -- aborting
```

There are no certificates in `/etc/ssl/certs`, but the code adds a dummy certificate (https://github.com/ansible/ansible/blob/e54178f904d826904e2456bd8fa711d13480c5f7/lib/ansible/module_utils/urls.py#L220-L221), which should work out of the box? 

Curl, wget both verify `https://mediately.slack.com` without a problem.

**Comment by nornagon** [comment]
I've also run into this issue, on OS X 10.9 (Mavericks).

**Comment by jure** [comment]
The original issue is in the proper format now (cc @ansibot).

**Comment by sivel** [comment]
Just to verify, do you run into this when using the bundled /usr/bin/python included with Mac, or are you using python from some place else such as homebrew or macports?

I have tested with the system python on 10.9 and 10.10 and cannot replicate the issue.

**Comment by jure** [comment]
Good point, this is Python 2.7.8, installed with homebrew. I added this info to the original comment.

**Comment by sivel** [comment]
If you apply the following change to `urls.py`, does it solve the problem?

```
diff --git a/lib/ansible/module_utils/urls.py b/lib/ansible/module_utils/urls.py
index 1280745..e86ae3a 100644
--- a/lib/ansible/module_utils/urls.py
+++ b/lib/ansible/module_utils/urls.py
@@ -219,6 +219,7 @@ class SSLValidationHandler(urllib2.BaseHandler):
         # Write the dummy ca cert if we are running on Mac OS X
         if platform == 'Darwin':
             os.write(tmp_fd, DUMMY_CA_CERT)
+            paths_checked.append('/usr/local/etc/openssl')

         # for all of the paths, find any  .crt or .pem files
         # and compile them into single temp file for use
```

**Comment by jure** [comment]
Yes it does.

```
TASK: [Send notification to Slack] ******************************************** 
ok: [localhost -> 127.0.0.1]
```

**Comment by nornagon** [comment]
I'm using the system python (2.7.6). The above patch doesn't fix the issue for me.

**Comment by sivel** [comment]
So, to clarify why that patch works for homebrew; Homebrew provided python is not built against the same libraries as the system provided python.  So that dummy cert code used to get the system built python to do its magic, does not work with homebrew python.

Currently, most libraries depend on the homebrew provided "openssl".  I'm not convinced it would _hurt_ anything to just go ahead and include `/usr/local/etc/openssl` regardless of homebrew or not.

**Comment by sivel** [comment]
@nornagon while your symptoms are the same, it is likely a different issue.  I would have to assume the OSX python<->openssl communication on your machine is broken in some way.

**Comment by nornagon** [comment]
```
$ python
>>> import requests
>>> requests.get('https://transcriptic.slack.com')
<Response [200]>
```

**Comment by sivel** [comment]
To be clear about the requests library, it bundles the mozilla ca cert bundle. Due to ansible not using requests, that is not a correct comparison.

The code that performs the SSL verification in ansible can be seen at https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/urls.py#L253

**Comment by nornagon** [comment]
Ah, I wasn't aware of that fact about requests!

Interestingly, I've seen this exact same error on a Linux system. I guess something about slack's certificate expired or changed recently.

**Comment by jimi-c** [comment]
Since this appears to be an issue with the `urls.py` code (as @sivel pointed out above), I'm going to go ahead and close this issue here, and I'll wait for the PR with the above fix in `ansible/ansible`.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!

**Comment by nornagon** [comment]
This fix doesn't work for me.
- Yosemite
- system python (2.7.6)
- `brew install openssl` puts a certificate in `/usr/local/etc/openssl/` called `cert.pem`
- ansible is checking `/usr/local/etc/openssl`
- `$ (cd ansible/; git rev-parse HEAD) # =>
  cd1cd2060bdee11a3996c29d109ed18ca3fdaf07`

```
TASK: [notify slack] **********************************************************
failed: [192.168.1.98] => {"failed": true}
msg: Failed to validate the SSL certificate for transcriptic.slack.com:443. Use validate_certs=no or make sure your managed systems have a valid CA certificate installed. Paths checked for this platform: /etc/ssl/certs, /etc/ansible, /usr/local/etc/openssl
```
