### ISSUE TITLE
Add more modes to the mysql_replication module

### ISSUE THREAD

**Issue by tersmitten** [ansible/ansible-modules-extras#979]
For instance `RESET SLAVE` and `RESET SLAVE ALL`.

**Comment by tersmitten** [comment]
[This article](https://www.percona.com/blog/2013/04/17/reset-slave-vs-reset-slave-all-disconnecting-a-replication-slave-is-easier-with-mysql-5-5/) explains the difference between `RESET SLAVE` and `RESET SLAVE ALL`.

**Comment by jimi-c** [comment]
# Closing This Ticket

Hi!

We believe the above commit should resolve this problem for you. This will also be included in the next major release.

If you continue seeing any problems related to this issue, or if you have any further questions, please let us know by stopping by one of the two mailing lists, as appropriate:
- https://groups.google.com/forum/#!forum/ansible-project - for user questions, tips, and tricks
- https://groups.google.com/forum/#!forum/ansible-devel - for strategy, future planning, and questions about writing code

Because this project is very active, we're unlikely to see comments made on closed tickets, but the mailing list is a great way to ask questions, or post if you don't think this particular issue is resolved.

Thank you!
